apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fluentd.serviceAccount.name }}
  namespace: {{ .Values.fluentd.serviceAccount.namespace }}
  labels:
{{- include "fluentd-labels" . | indent 2 }}
