serviceAccount:
  name: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::022865527167:role/cert-manager-role
extraArgs:
- --issuer-ambient-credentials
securityContext:
  fsGroup: 1001
clusterResourceNamespace: cert-manager
global:
  leaderElection:
    namespace: cert-manager
installCRDs: true
