---
  - name: Ansible wazuh indexer deployment 
    gather_facts: false
    become: yes
    become_user: root
    hosts: wazuh_indexer

    tasks:
      - name: Increase max_map_count on your host (Linux)
        ansible.builtin.shell: sysctl -w vm.max_map_count=262144

      - name: Copy wazuh certification
        ansible.builtin.copy:
          src: ./wazuh-certificates
          dest: ./wazuh-certificates
          owner: root
          group: root
          mode: '755'

      - name: Copy wazuh-indexer.yml config file
        ansible.builtin.copy:
          src: ./wazuh-indexer.yml
          dest: ./wazuh-indexer.yml
          owner: root
          group: root
          mode: '0644'

      - name: Copy file with owner and permissions
        ansible.builtin.copy:
          src: ./internal_users.yml
          dest: ./internal_users.yml
          owner: root
          group: root
          mode: '0644'

      - name: Run wazuh-indexer container
        community.general.docker_container:
          name: wazuh-indexer
          image: wazuh/wazuh-indexer:4.3.10
          network_mode: host
          volumes:
            - wazuh-indexer-data:/var/lib/wazuh-indexer
            - ./wazuh-certificates/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
            - ./wazuh-certificates/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
            - ./wazuh-certificates/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
            - ./wazuh-certificates/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
            - ./wazuh-certificates/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
            - ./wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
            - ./internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
          env:
            OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
          ulimits:
            - "memlock:-1:-1"
            - "nofile:65536:65536"
          
