apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: test.golang-admission-controller
webhooks:
- name: test.golang-admission-controller
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: default
      name: golang-admission-controller
      path: "/"
    caBundle: CA_BUNDLE
  admissionReviewVersions: ["v1"]
  sideEffects: None
