apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-armor
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apparmor
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/app-armor
    repoURL: https://github.com/stevan95/INFRA
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
