apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kibana.name }}
  namespace: {{ .Values.kibana.namespace }}
  labels:
{{- include "kibana-labels" . | indent 2 }}
spec:
  replicas: {{ .Values.kibana.replicas }}
  selector:
    matchLabels:
{{- include "kibana-labels-selectors" . | indent 4 }}
  template:
    metadata:
      labels:
{{- include "kibana-labels-selectors" . | indent 6 }}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      containers:
      - name: {{ .Values.kibana.name }}
        image: {{ .Values.kibana.image }}:{{ .Chart.AppVersion }}
        resources:
          {{- toYaml $.Values.kibana.resources | nindent 10 }}
        env:
        {{- range .Values.kibana.envs }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        ports:
        {{- range .Values.kibana.ports }}
        - containerPort: {{ .containerPort }}
          name: {{ .name }}
          protocol: {{ .protocol }}
        {{- end }}
