name: security-scan-image
on:
  push:
    branches:
      - main

jobs:
  security-image-scan:
    name: Docker Image Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: INFRA

      - name: Build an image from Dockerfile
        run: |
          cd INFRA/code/simple-app/
          path=`pwd`
          basename $path
          docker build -t `basename $path`:sec-test .

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(uname -s)_$(uname -m).deb
          sudo dpkg -i trivy_$(uname -s)_$(uname -m).deb

      - name: Run Trivy Image Scan
        run: |
          trivy image `basename $path`:sec-test -format sarif -o trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
